### ISSUE TITLE
Punctum Cavum bug

### ISSUE THREAD

**Issue by SirPL** [frmatthew/exsurge#25]
I've found bug in Punctum Cavum behavior. There are some examples:
`(c3) A(hrgrfr)`
![1](https://cloud.githubusercontent.com/assets/11311649/13978555/45a8e59a-f0d2-11e5-98de-4fad497cb47f.png)
As you can see, intervals between cavums are not applied.

`(c3) A(hggr)`
![2](https://cloud.githubusercontent.com/assets/11311649/13978591/976dbf7c-f0d2-11e5-9d5b-f7af7568d2f5.png)
It seems that cavum applies interval equal to the interval between previous two non-cavum neumes

`(c3) A(hggrgrgr)`
![3](https://cloud.githubusercontent.com/assets/11311649/13978631/f48afd00-f0d2-11e5-8054-5b59dcc26983.png)
Now all cavums went 3 _tones_ down

`(c3) A(fghrhrhrhrhrhrhrhrhrhrhrhrhr)`
![4](https://cloud.githubusercontent.com/assets/11311649/13978746/bd5c40b8-f0d3-11e5-9df5-425ef5572a30.png)

_No further research has been done so far._

**Comment by frmatthew** [comment]
Thank you...c1544d9d0194d081b59f36192f06e1c839196c13 fixes part of the problem, that is, the puctum cavum going onto the right staff line. The spacing issue remains which is a bigger issue and needs me to revamp the spacing logic in general. For now I'm going to close this issue and open another to resolve the spacing issue.
