### ISSUE TITLE
Another Punctum Cavum Error

### ISSUE THREAD

**Issue by SirPL** [frmatthew/exsurge#32]
I've found another bug with punctum cavum: When there is Punctum Cavum followed by Punctum Cuadratum, both are rendered as Cuadratums.
`(c3) Pu(hhrhr)`
![quadratum distropha](https://cloud.githubusercontent.com/assets/11311649/14024806/52033650-f1eb-11e5-9857-821cb537b5b7.png)

I have prepared a fix for that, but I need to know how you are _compiling_ multiple js's into one file (what tool are you using - any tutorial is more than welcome)

**Comment by frmatthew** [comment]
Thanks for the heads up, yes, this is an issue with the gabc interpreter, which needs a lot of work in how to assemble neumes from notes. I'll get on it.

I am using Node.js to develop it...easiest way to get started (once you have Node.js installed) is to open a console or command line in the exsurge root folder, install the Node dependencies, and run `npm run dev` which will dynamically compile the files as they are edited. If all of this is unfamiliar to you, then you'll have to learn some Node.js first...

**Comment by frmatthew** [comment]
I have fixed some of the cavum glyph problems, but the gabc interpreter still needs work, sorry, this is all a work in progress at the moment.

**Comment by SirPL** [comment]
Don't be sorry. I am aware of that and I want you to know that I very appreciate your work (really). I would like to contribute, but I need some time to went through the code and understand its basics.
BTW. Thank you for the `node`command - auto compiler works like a charm
