### ISSUE TITLE
Fix build process of the dist files

### ISSUE THREAD

**Issue by frmatthew** [frmatthew/exsurge#39]
Currently the dist files are part of the dev repository, so that each update made will also regenerate the dist files and they get committed as part of commits. This makes for messy commit histories and unnecessary repo clutter.

Some options:
- gitignore the dist folder?
- use jenkins/github to automate the build process?
- put the dist files in a separate repo?

**Comment by bbloomf** [comment]
Could you set it up to gitignore the dist folder AND also set up jenkins/github to automate the build process, and still commit the dist foler?  I think that would make the most sense to me.

**Comment by frmatthew** [comment]
After evaluating Docker, drone.io, travis ci, and codeship.io, I decided to integrated it with codeship.io and surge.sh: on every git push to the master branch, codeship rebuilds the lib. Then it gets deployed to surge.sh (actually, the domain ex.surge.sh, which is rather providential). I think think surge.sh can serve as the CDN to distribute the dist files.

I only have the free codeship.io account, so I'm not sure it it will work long term or not, depends on the number of monthly builds I guess...
