### ISSUE TITLE
Scandicus subpunctis = "crash"

### ISSUE THREAD

**Issue by SirPL** [frmatthew/exsurge#60]
Entering `efhg` causes error:
`Uncaught TypeError: Cannot read property 'bounds' of null`

**Comment by frmatthew** [comment]
Thank you...with commit 1b75f995801663f0133d4cc33fc85d38ce282e5a I have fixed the crash, though at this point exsurge is simply rendering a scandicus flexus as a podatus followed by a clivis. Can you confirm what the expected notations look like for `efhg` in gabc?

**Comment by SirPL** [comment]
There's the expected output:
![expected](https://cloud.githubusercontent.com/assets/11311649/14227098/0307bcc2-f8f5-11e5-8c3c-98cee80c8f93.png)
