### ISSUE TITLE
Bar lines immediately after new system

### ISSUE THREAD

**Issue by bbloomf** [frmatthew/exsurge#65]
I'm not certain, but I think there is a rule that a system shouldn't start with a bar line; anyway it looks strange to me when it puts a line break such that it starts with a bar line.

**Comment by frmatthew** [comment]
I fixed this and closed the issue, but just realized that there are other notations that probably shouldn't start a new line... clefs for instance? Any others?

**Comment by olivierberten** [comment]
You can start a new line with a new clef, as long as the custos is set according to the new clef.

**Comment by frmatthew** [comment]
Thanks @olivierberten: In the case where the clef change is the first notation for the line, is the previous clef supposed to be displayed first, or does the new clef simply take the place of the previous clef as the first on the line? I.e., is this correct:

![clef change](https://cloud.githubusercontent.com/assets/17261076/14436599/515b2fe2-ffd2-11e5-979e-b3bde24a4cad.png)

or should the c3 clef simply not be rendered on the second line?

**Comment by olivierberten** [comment]
This is indeed a mistake... c3 shouldn't be rendered.

**Comment by frmatthew** [comment]
Thanks @olivierberten, the above commit should resolve the clef change at the start of the line now.
