### ISSUE TITLE
`ctxt.lyricTextColor` is not heeded

### ISSUE THREAD

**Issue by tukusejssirs** [frmatthew/exsurge#90]
I want to change the foreground color of all elements. I can change the colour of dividers (`ctxt.dividerLineColor`), neumes (`ctxt.neumeLineColor`) and staff lines (`ctxt.staffLineColor`), but the following three does not work:
- `ctxt.lyricTextColor`;
- `ctxt.annotationTextColor`;
- `ctxt.dropCapTextColor`.

Is it a bug?

**Comment by frmatthew** [comment]
Yes, it's probably a bug.

I released this as an experimental project, but haven't done any work on it for about four years. You could try looking at some of the forks of the project and seeing if others have made more progress on it, and possibly improved rendering.

**Comment by tukusejssirs** [comment]
I see, @frmatthew. Thanks anyway for this awesome project. Could you archive the project or otherwise label it as non-maintained? :wink:

---

Well, I looked at the forks and as far as I see it right, the one made by @bbloomf has 200+ ahead commits, so he could help me out, however, he disabled the issue tracker his fork. @bbloomf, could you help me with this and #91? Thanks in advance! :pray:

**Comment by tukusejssirs** [comment]
@bbloomf, `ctxt.lyricTextColor` works as expected in your fork, however, the issue described in #91 does not.

Because of this, I’ll close this issue.
